config/routes.rb
Canyousellme::Application.routes.draw do

  resources :pitch_submissions   
  resources :pitchers do
    resources :pitches
  end

  get "static_pages/home"
  get "static_pages/help"

  get "pitches/new"
  get "pitches/preview"

  get "pitchers/:pitcher_id/pitches", to: 'pitches#index'
  get "pitches/submit"  
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :pitchers

   root :to => 'pitchers#index'

end

app/models/pitcher.rb
class Pitcher < ActiveRecord::Base
  attr_accessible :email, :name    
  validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false } 
  has_many :pitches
    def self.from_omniauth(auth)
      where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
    end   
    
    def pitches_for_pitcher(pitcher_id)                   
      @pitcher = Pitcher.find_by_id(pitcher_id)
      pitches = @pitcher.pitches.all    
      return pitches
    end                      
    
  
  end

app/controllers/pitchers_controller.rb
class PitchersController < ApplicationController
  before_action :set_pitcher, only: [:show, :edit, :update, :destroy]

  # GET /pitchers
  # GET /pitchers.json
  def index
    @pitchers = Pitcher.all
  end

  # GET /pitchers/1
  # GET /pitchers/1.json
  def show
  end

  # GET /pitchers/new
  def new
    @pitcher = Pitcher.new
  end

  # GET /pitchers/1/edit
  def edit
  end

  # POST /pitchers
  # POST /pitchers.json
  def create
    @pitcher = Pitcher.new(pitcher_params)

    respond_to do |format|
      if @pitcher.save
        format.html { redirect_to @pitcher, notice: 'Pitcher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pitcher }
      else
        format.html { render action: 'new' }
        format.json { render json: @pitcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pitchers/1
  # PATCH/PUT /pitchers/1.json
  def update
    respond_to do |format|
      if @pitcher.update(pitcher_params)
        format.html { redirect_to @pitcher, notice: 'Pitcher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pitcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitchers/1
  # DELETE /pitchers/1.json
  def destroy
    @pitcher.destroy
    respond_to do |format|
      format.html { redirect_to pitchers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pitcher
      @pitcher = Pitcher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pitcher_params
      params[:pitcher, :name, :email]
    end
end

app/helpers/pitchers_helper.rb
module PitchersHelper
end

app/views/pitchers/_form.html.erb
<% if @pitcher.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@pitcher.errors.count, "error") %> prohibited this pitcher from being saved:</h2>

    <ul>
    <% @pitcher.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= simple_form_for @pitcher do |f| %>  
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.button :submit %>
<% end %>

app/views/pitchers/edit.html.erb
<h1>Editing pitcher</h1>

<%= render 'form' %>

<%= link_to 'Show', @pitcher %> |
<%= link_to 'Back', pitchers_path %>

app/views/pitchers/index.html.erb
<h1>Listing pitchers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pitchers.each do |pitcher| %>
  <tr>
    <td><%= pitcher.name %></td>
    <td><%= pitcher.email %></td>
    <td><%= link_to 'Show', pitcher %></td>
    <td><%= link_to 'Edit', edit_pitcher_path(pitcher) %></td>
    <td><%= link_to 'Destroy', pitcher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pitcher', new_pitcher_path %>

app/views/pitchers/new.html.erb
<h1>New pitcher</h1>

<%= render 'form' %>

<%= link_to 'Back', pitchers_path %>

app/views/pitchers/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Welcome to <%= @pitcher.name %>'s homepage</h1>
<p>
  <b>Name:</b>
  <%= @pitcher.name %>
</p>

<p>
  <b>Email:</b>
  <%= @pitcher.email %>
</p>

<% pitches = @pitcher.pitches_for_pitcher(@pitcher.id) %>     
<% pitches.each do |p| %> 
  <p>
    <%= link_to "view", pitcher_pitch_path(@pitcher.id, p.id) %>     
    <%= render :partial => 'pitches/youtube_video', locals: {pitch: p, size: "thumb"}  %>
    
  </p>
<% end %>

<%= link_to 'New Pitch', new_pitcher_pitch_path(@pitcher.id) %> 
<%= link_to 'Edit', edit_pitcher_path(@pitcher) %> |
<%= link_to 'Back', pitchers_path %>