config/routes.rb
Canyousellme::Application.routes.draw do

  resources :pitch_submissions   
  resources :pitchers do
    resources :pitches
  end

  get "static_pages/home"
  get "static_pages/help"

  get "pitches/new"
  get "pitches/preview"

  get "pitchers/:pitcher_id/pitches", to: 'pitches#index'
  get "pitches/submit"  
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :pitchers

   root :to => 'pitchers#index'

end

app/models/pitch_submission.rb
class PitchSubmission < ActiveRecord::Base
end

app/controllers/pitch_submissions_controller.rb
class PitchSubmissionsController < ApplicationController
  # GET /pitch_submissions
  # GET /pitch_submissions.json
  def index
    @pitch_submissions = PitchSubmission.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pitch_submissions }
    end
  end

  # GET /pitch_submissions/1
  # GET /pitch_submissions/1.json
  def show
    @pitch_submission = PitchSubmission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pitch_submission }
    end
  end

  # GET /pitch_submissions/new
  # GET /pitch_submissions/new.json
  def new
    @pitch_submission = PitchSubmission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pitch_submission }
    end
  end

  # GET /pitch_submissions/1/edit
  def edit
    @pitch_submission = PitchSubmission.find(params[:id])
  end

  # POST /pitch_submissions
  # POST /pitch_submissions.json
  def create
    @pitch_submission = PitchSubmission.new(params[:pitch_submission])

    respond_to do |format|
      if @pitch_submission.save
        format.html { redirect_to @pitch_submission, notice: 'Pitch submission was successfully created.' }
        format.json { render json: @pitch_submission, status: :created, location: @pitch_submission }
      else
        format.html { render action: "new" }
        format.json { render json: @pitch_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pitch_submissions/1
  # PUT /pitch_submissions/1.json
  def update
    @pitch_submission = PitchSubmission.find(params[:id])

    respond_to do |format|
      if @pitch_submission.update_attributes(params[:pitch_submission])
        format.html { redirect_to @pitch_submission, notice: 'Pitch submission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pitch_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitch_submissions/1
  # DELETE /pitch_submissions/1.json
  def destroy
    @pitch_submission = PitchSubmission.find(params[:id])
    @pitch_submission.destroy

    respond_to do |format|
      format.html { redirect_to pitch_submissions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pitch_submissions_helper.rb
module PitchSubmissionsHelper
end

app/views/pitch_submissions/_form.html.erb
<%= form_for(@pitch_submission) do |f| %>
  <% if @pitch_submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pitch_submission.errors.count, "error") %> prohibited this pitch_submission from being saved:</h2>

      <ul>
      <% @pitch_submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pitch_id %><br />
    <%= f.number_field :pitch_id %>
  </div>
  <div class="field">
    <%= f.label :pitcher_id %><br />
    <%= f.number_field :pitcher_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pitch_submissions/edit.html.erb
<h1>Editing pitch_submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @pitch_submission %> |
<%= link_to 'Back', pitch_submissions_path %>

app/views/pitch_submissions/index.html.erb
<h1>Listing pitch_submissions</h1>

<table>
  <tr>
    <th>Pitch</th>
    <th>Pitcher</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pitch_submissions.each do |pitch_submission| %>
  <tr>
    <td><%= pitch_submission.pitch_id %></td>
    <td><%= pitch_submission.pitcher_id %></td>
    <td><%= link_to 'Show', pitch_submission %></td>
    <td><%= link_to 'Edit', edit_pitch_submission_path(pitch_submission) %></td>
    <td><%= link_to 'Destroy', pitch_submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pitch submission', new_pitch_submission_path %>

app/views/pitch_submissions/new.html.erb
<h1>New pitch_submission</h1>

<%= render 'form' %>

<%= link_to 'Back', pitch_submissions_path %>

app/views/pitch_submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pitch:</b>
  <%= @pitch_submission.pitch_id %>
</p>

<p>
  <b>Pitcher:</b>
  <%= @pitch_submission.pitcher_id %>
</p>


<%= link_to 'Edit', edit_pitch_submission_path(@pitch_submission) %> |
<%= link_to 'Back', pitch_submissions_path %>